
let wanted_pieces = [
  ["ARMOR_OF_MAGMA_CHESTPLATE", "#FF93"],
  ["ARMOR_OF_MAGMA_LEGGINGS", "#FF93"],
  ["ARMOR_OF_MAGMA_BOOTS", "#FF93"],
  ["ARMOR_OF_MAGMA_HELMET", "#FF93"],
  ["SUPERIOR_DRAGON_CHESTPLATE", "#F2DF11"],
  ["SUPERIOR_DRAGON_LEGGINGS", "#F2DF11"],
  ["SUPERIOR_DRAGON_BOOTS", "#F25D18"],
  ["STRONG_DRAGON_CHESTPLATE", "#D91E41"],
  ["STRONG_DRAGON_LEGGINGS", "#E09419"],
  ["STRONG_DRAGON_BOOTS", "#F0D124"],
  ["WISE_DRAGON_CHESTPLATE", "#29F0E9"],
  ["WISE_DRAGON_LEGGINGS", "#29F0E9"],
  ["WISE_DRAGON_BOOTS", "#29F0E9"],
  ["YOUNG_DRAGON_CHESTPLATE", "#DDE4F"],
  ["YOUNG_DRAGON_LEGGINGS", "#DDE4F"],
  ["YOUNG_DRAGON_BOOTS", "#DDE4F"],
  ["UNSTABLE_DRAGON_CHESTPLATE", "#B212E3"],
  ["UNSTABLE_DRAGON_LEGGINGS", "#B212E3"],
  ["UNSTABLE_DRAGON_BOOTS", "#B212E3"],
  ["OLD_DRAGON_CHESTPLATE", "#F0E6AA"],
  ["OLD_DRAGON_LEGGINGS", "#F0E6AA"],
  ["OLD_DRAGON_BOOTS", "#F0E6AA"],
  ["PROTECTOR_DRAGON_CHESTPLATE", "#99978B"],
  ["PROTECTOR_DRAGON_LEGGINGS", "#99978B"],
  ["PROTECTOR_DRAGON_BOOTS", "#99978B"],
  ["TARANTULA_HELMET", "#0"],
  ["TARANTULA_LEGGINGS", "#0"],
  ["SHARK_SCALE_CHESTPLATE", "#2CA6"],
  ["SHARK_SCALE_LEGGINGS", "#2CA6"],
  ["SHARK_SCALE_BOOTS", "#2CA6"],
  ["ANGLER_CHESTPLATE", "#B004F"],
  ["ANGLER_LEGGINGS", "#B004F"],
  ["ANGLER_BOOTS", "#B004F"],
  ["ANGLER_HELMET", "#B004F"],
  ["SQUID_BOOTS", "#0"],
  ["BAT_PERSON_HELMET", "#0"],
  ["BAT_PERSON_CHESTPLATE", "#0"],
  ["BAT_PERSON_LEGGINGS", "#0"],
  ["BAT_PERSON_BOOTS", "#0"],
  ["FARM_ARMOR_HELMET", "#FFD7"],
  ["FARM_ARMOR_CHESTPLATE", "#FFD7"],
  ["FARM_ARMOR_LEGGINGS", "#FFD7"],
  ["FARM_ARMOR_BOOTS", "#FFD7"],
  ["FARMER_BOOTS", "#CC55"],
  ["RANCHERS_BOOTS", "#CC55"],
  ["FARM_SUIT_HELMET", "#FFFF"],
  ["FARM_SUIT_CHESTPLATE", "#FFFF"],
  ["FARM_SUIT_LEGGINGS", "#FFFF"],
  ["FARM_SUIT_BOOTS", "#FFFF"],
  ["SPEEDSTER_HELMET", "#E0FCF7"],
  ["SPEEDSTER_CHESTPLATE", "#E0FCF7"],
  ["SPEEDSTER_LEGGINGS", "#E0FCF7"],
  ["SPEEDSTER_BOOTS", "#E0FCF7"],
  ["CACTUS_HELMET", "#FF"],
  ["CACTUS_CHESTPLATE", "#FF"],
  ["CACTUS_LEGGINGS", "#FF"],
  ["CACTUS_BOOTS", "#FF"],
  ["LEAFLET_CHESTPLATE", "#4DCC4D"],
  ["LEAFLET_LEGGINGS", "#4DCC4D"],
  ["LEAFLET_BOOTS", "#4DCC4D"],
  ["MINER_OUTFIT_HELMET", "#7A7964"],
  ["MINER_OUTFIT_CHESTPLATE", "#7A7964"],
  ["MINER_OUTFIT_LEGGINGS", "#7A7964"],
  ["MINER_OUTFIT_BOOTS", "#7A7964"],
  ["MUSIC_PANTS", "#4CFD3"],
  ["MUSHROOM_HELMET", "#FF"],
  ["MUSHROOM_CHESTPLATE", "#FF"],
  ["MUSHROOM_LEGGINGS", "#FF"],
  ["MUSHROOM_BOOTS", "#FF"],
  ["GUARDIAN_CHESTPLATE", "#117391"],
  ["CREEPER_LEGGINGS", "#7AE82C"],
  ["EMERALD_ARMOR_HELMET", "#FF"],
  ["EMERALD_ARMOR_CHESTPLATE", "#FF"],
  ["EMERALD_ARMOR_LEGGINGS", "#FF"],
  ["EMERALD_ARMOR_BOOTS", "#FF"],
  ["PUMPKIN_HELMET", "#EDAA36"],
  ["PUMPKIN_CHESTPLATE", "#EDAA36"],
  ["PUMPKIN_LEGGINGS", "#EDAA36"],
  ["PUMPKIN_BOOTS", "#EDAA36"],
  ["ARMOR_OF_PACK_HELMET", "#FFFFFF"],
  ["ARMOR_OF_PACK_CHESTPLATE", "#FF"],
  ["SPONGE_CHESTPLATE", "#FFDC51"],
  ["SPONGE_LEGGINGS", "#FFDC51"],
  ["SPONGE_BOOTS", "#FFDC51"],
  ["OBSIDIAN_CHESTPLATE", "#0"],
  ["LAPIS_ARMOR_CHESTPLATE", "#FF"],
  ["LAPIS_ARMOR_LEGGINGS", "#FF"],
  ["LAPIS_ARMOR_BOOTS", "#FF"],
  ["CHEAP_TUXEDO_CHESTPLATE", "#383838"],
  ["CHEAP_TUXEDO_LEGGINGS", "#C7C7C7"],
  ["CHEAP_TUXEDO_BOOTS", "#383838"],
  ["FANCY_TUXEDO_BOOTS", "#332A2A"],
  ["FANCY_TUXEDO_LEGGINGS", "#D4D4D4"],
  ["FANCY_TUXEDO_CHESTPLATE", "#332A2A"],
  ["ELEGANT_TUXEDO_BOOTS", "#191919"],
  ["ELEGANT_TUXEDO_BOOTS_TUXEDO_LEGGINGS", "#FEFDFC"],
  ["ELEGANT_TUXEDO_CHESTPLATE", "#191919"],
]


let fairy_crystal_colors = [
    '#1F003', // crystal
    '#46085E',
    '#54146E',
    '#5D1C78',
    '#63237D',
    '#6A2C82',
    '#7E4196',
    '#8E51A6',
    '#9C64B3',
    '#A875BD',
    '#B88BC9',
    '#C6A3D4',
    '#D9C1E3',
    '#E5D1ED',
    '#EFE1F5',
    '#FCF3FF',
    '#660066', //fairy
    '#660033',
    '#99004C',
    '#CC0066',
    '#FF007F',
    '#FF3399',
    '#FF66B2',
    '#FF99CC',
    '#FFCCE5',
    '#FF99CC',
    '#FF66B2',
    '#FF3399',
    '#FF007F',
    '#CC0066',
    '#99004C',
    '#660033',
    '#660066',
    '#990099',
    '#CC00CC',
    '#FF00FF',
    '#FF33FF',
    '#FF66FF',
    '#FF99FF',
    '#FFCCFF',
    '#E5CCFF',
    '#CC99FF',
    '#B266FF',
    '#9933FF',
    '#7F00FF',
    '#6600CC',
    '#4C0099',
    '#330066',
    '#4C0099',
    '#6600CC',
    '#7F00FF',
    '#9933FF',
    '#B266FF',
    '#CC99FF',
    '#E5CCFF',
    '#FFCCFF',
    '#FF99FF',
    '#FF66FF',
    '#FF33FF',
    '#FF00FF',
    '#CC00CC',
    '#990099',
	'#0'	
]

export {fairy_crystal_colors, wanted_pieces}
//
// var wither_colors = [
//     '#1CD4E4',
//     '#17A8C4',
//     '#1793C4',
//     '#E76E3C',
//     '#E75C3C',
//     '#E7413C',
//     '#88837E',
//     '#65605A',
//     '#45413C',
//     '#8969C8',
//     '#5D2FB9',
//     '#4A14B7'
// ]
//
// var tux_colors = [
//     '#191919',
//     '#FEFDFC',
//     '#C7C7C7',
//     '#383838',
//     '#332A2A',
//     '#D4D4D4'
// ]
